@baseUrl = http://localhost:4000/api

# @name register
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "john doe",
	"email": "johndddoe@example.com",
	"password": "password123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "johndddoe@example.com",
	"password": "wef"
}
