@baseUrl = http://localhost:4000/api
@accessToken = {{authenticate.response.body.access_token}}
@walletId = {{create_wallet.response.body.id}}
@categoryId = {{create_investment_category.response.body.id}}
@investmentId = {{create_investment.response.body.id}}

# @name register
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "dummy",
	"email": "dummy@example.com",
	"password": "password123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "dummy@example.com",
	"password": "password123"
}

###

# @name create_wallet
POST {{baseUrl}}/wallets
Content-Type: application/json
Authorization:	Bearer {{accessToken}}

{
	"name": "dummy wallet name"
}

###

# @name create_investment_category
POST {{baseUrl}}/investments/categories
Content-Type: application/json
Authorization:	Bearer {{accessToken}}

{
	"name": "dummy category name"
}

###

# @name create_investment
POST {{baseUrl}}/investments
Content-Type: application/json
Authorization:	Bearer {{accessToken}}

{
	"name": "dummy investment",
	"description": "dummy description",
	"source": "dummy source",
	"value": 100050,
	"category_id": "{{categoryId}}",
	"wallet_id": "{{walletId}}"
}

###

# @name withdraw_investment
POST {{baseUrl}}/investments/{{walletId}}/withdraw/{{investmentId}}
Content-Type: application/json
Authorization:	Bearer {{accessToken}}

{
	"resultant_value": 200050
}