@baseUrl = http://localhost:4000/api
@accessToken = {{authenticate.response.body.access_token}}

# @name register
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "dummy",
	"email": "dummy@example.com",
	"password": "password123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "dummy@example.com",
	"password": "password123"
}

###

# @name create_wallet
POST {{baseUrl}}/wallets
Content-Type: application/json
Authorization:	Bearer {{accessToken}}

{
	"name": "dummy name"
}

